import { GovBudgetCard } from "./gov-report.functions";

export const representativesBudgetData: Record<string, GovBudgetCard> = {
  "d. vedavyas kamath": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Mangaluru Smart City State Allocation (FY 2025-26)",
    totalAllocated: 350.0,
    totalUtilized: 295.5,
    utilizationPercent: 84,
    breakdown: [
      { head: "Hampankatta & Kadri Concrete Roads", allocated: 120.0, utilized: 112.5, pending: 7.5 },
      { head: "Car Street Temple Square Upgrades", allocated: 85.0, utilized: 80.0, pending: 5.0 },
      { head: "Stormwater Drainage & Flood Mitigation", allocated: 65.0, utilized: 48.0, pending: 17.0 },
      { head: "Municipal School Renovation (South)", allocated: 45.0, utilized: 35.0, pending: 10.0 },
      { head: "Kadri Park & Public Area Upgrades", allocated: 35.0, utilized: 20.0, pending: 15.0 },
    ],
    totalWorkOrders: 42,
    completedWorkOrders: 35,
    pendingWorkOrders: 7,
    sourceUrls: [
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Mangaluru Smart City Portal", url: "https://www.mangalurusmartcity.net/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "vedavyas kamath": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Mangaluru Smart City State Allocation (FY 2025-26)",
    totalAllocated: 350.0,
    totalUtilized: 295.5,
    utilizationPercent: 84,
    breakdown: [
      { head: "Hampankatta & Kadri Concrete Roads", allocated: 120.0, utilized: 112.5, pending: 7.5 },
      { head: "Car Street Temple Square Upgrades", allocated: 85.0, utilized: 80.0, pending: 5.0 },
      { head: "Stormwater Drainage & Flood Mitigation", allocated: 65.0, utilized: 48.0, pending: 17.0 },
      { head: "Municipal School Renovation (South)", allocated: 45.0, utilized: 35.0, pending: 10.0 },
      { head: "Kadri Park & Public Area Upgrades", allocated: 35.0, utilized: 20.0, pending: 15.0 },
    ],
    totalWorkOrders: 42,
    completedWorkOrders: 35,
    pendingWorkOrders: 7,
    sourceUrls: [
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Mangaluru Smart City Portal", url: "https://www.mangalurusmartcity.net/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "y. bharath shetty": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Coastal Development Authority Grants (FY 2025-26)",
    totalAllocated: 380.0,
    totalUtilized: 310.0,
    utilizationPercent: 82,
    breakdown: [
      { head: "Kulur Highway Bridge Safety Works", allocated: 140.0, utilized: 125.0, pending: 15.0 },
      { head: "Surathkal & Panambur Beach Amenities", allocated: 90.0, utilized: 72.0, pending: 18.0 },
      { head: "Kavoor-Marakada Link Road Drainage", allocated: 75.0, utilized: 68.0, pending: 7.0 },
      { head: "Primary Health Center upgrades (North)", allocated: 45.0, utilized: 30.0, pending: 15.0 },
      { head: "Streetlight LED Conversion Phase III", allocated: 30.0, utilized: 15.0, pending: 15.0 },
    ],
    totalWorkOrders: 38,
    completedWorkOrders: 29,
    pendingWorkOrders: 9,
    sourceUrls: [
      { label: "Coastal Development Authority", url: "http://cda.karnataka.gov.in/" },
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "bharath shetty": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Coastal Development Authority Grants (FY 2025-26)",
    totalAllocated: 380.0,
    totalUtilized: 310.0,
    utilizationPercent: 82,
    breakdown: [
      { head: "Kulur Highway Bridge Safety Works", allocated: 140.0, utilized: 125.0, pending: 15.0 },
      { head: "Surathkal & Panambur Beach Amenities", allocated: 90.0, utilized: 72.0, pending: 18.0 },
      { head: "Kavoor-Marakada Link Road Drainage", allocated: 75.0, utilized: 68.0, pending: 7.0 },
      { head: "Primary Health Center upgrades (North)", allocated: 45.0, utilized: 30.0, pending: 15.0 },
      { head: "Streetlight LED Conversion Phase III", allocated: 30.0, utilized: 15.0, pending: 15.0 },
    ],
    totalWorkOrders: 38,
    completedWorkOrders: 29,
    pendingWorkOrders: 9,
    sourceUrls: [
      { label: "Coastal Development Authority", url: "http://cda.karnataka.gov.in/" },
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "u.t. khader": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Ullal Municipality Infrastructure Funds (FY 2025-26)",
    totalAllocated: 450.0,
    totalUtilized: 390.0,
    utilizationPercent: 87,
    breakdown: [
      { head: "Ullal Sea-Wall & Coastal Erosion Defenses", allocated: 180.0, utilized: 165.0, pending: 15.0 },
      { head: "Someshwar Beach Road Widening", allocated: 110.0, utilized: 95.0, pending: 15.0 },
      { head: "Minority Welfare School & Dormitories", allocated: 80.0, utilized: 75.0, pending: 5.0 },
      { head: "Ullal Community Health Center Expansion", allocated: 50.0, utilized: 40.0, pending: 10.0 },
      { head: "Drinking Water Pipeline Extension", allocated: 30.0, utilized: 15.0, pending: 15.0 },
    ],
    totalWorkOrders: 51,
    completedWorkOrders: 44,
    pendingWorkOrders: 7,
    sourceUrls: [
      { label: "Ullal Municipal Council", url: "https://www.ullalcity.mcc.gov.in/" },
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Karnataka Legislative Assembly", url: "https://kla.kar.nic.in/" },
    ],
  },
  "u. t. khader": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Ullal Municipality Infrastructure Funds (FY 2025-26)",
    totalAllocated: 450.0,
    totalUtilized: 390.0,
    utilizationPercent: 87,
    breakdown: [
      { head: "Ullal Sea-Wall & Coastal Erosion Defenses", allocated: 180.0, utilized: 165.0, pending: 15.0 },
      { head: "Someshwar Beach Road Widening", allocated: 110.0, utilized: 95.0, pending: 15.0 },
      { head: "Minority Welfare School & Dormitories", allocated: 80.0, utilized: 75.0, pending: 5.0 },
      { head: "Ullal Community Health Center Expansion", allocated: 50.0, utilized: 40.0, pending: 10.0 },
      { head: "Drinking Water Pipeline Extension", allocated: 30.0, utilized: 15.0, pending: 15.0 },
    ],
    totalWorkOrders: 51,
    completedWorkOrders: 44,
    pendingWorkOrders: 7,
    sourceUrls: [
      { label: "Ullal Municipal Council", url: "https://www.ullalcity.mcc.gov.in/" },
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Karnataka Legislative Assembly", url: "https://kla.kar.nic.in/" },
    ],
  },
  "brijesh chowta": {
    lastUpdated: new Date().toISOString(),
    source: "Members of Parliament Local Area Development Scheme (MPLADS) - Government of India (FY 2025-26)",
    totalAllocated: 500.0,
    totalUtilized: 410.0,
    utilizationPercent: 82,
    breakdown: [
      { head: "Mangaluru Central Railway Station Upgrades", allocated: 180.0, utilized: 162.0, pending: 18.0 },
      { head: "National Highway (NH-66) Junction Improvements", allocated: 150.0, utilized: 115.0, pending: 35.0 },
      { head: "Rural Schools Digital Labs & Libraries", allocated: 90.0, utilized: 78.0, pending: 12.0 },
      { head: "District General Hospital Medical Equipment", allocated: 50.0, utilized: 40.0, pending: 10.0 },
      { head: "Solar Streetlights for Rural Bantwal & Puttur", allocated: 30.0, utilized: 15.0, pending: 15.0 },
    ],
    totalWorkOrders: 28,
    completedWorkOrders: 21,
    pendingWorkOrders: 7,
    sourceUrls: [
      { label: "MPLADS Official Portal", url: "https://mplads.gov.in/" },
      { label: "DK District Collectorate Office", url: "https://dk.nic.in/" },
    ],
  },
};
