import { GovBudgetCard } from "./gov-report.functions";

export const representativesBudgetData: Record<string, GovBudgetCard> = {
  "d. vedavyas kamath": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Mangaluru Smart City State Allocation (FY 2025-26)",
    totalAllocated: 350.0,
    totalUtilized: 295.5,
    utilizationPercent: 84,
    breakdown: [
      { head: "Hampankatta & Kadri Concrete Roads", allocated: 120.0, utilized: 112.5, pending: 7.5 },
      { head: "Car Street Temple Square Upgrades", allocated: 85.0, utilized: 80.0, pending: 5.0 },
      { head: "Stormwater Drainage & Flood Mitigation", allocated: 65.0, utilized: 48.0, pending: 17.0 },
      { head: "Municipal School Renovation (South)", allocated: 45.0, utilized: 35.0, pending: 10.0 },
      { head: "Kadri Park & Public Area Upgrades", allocated: 35.0, utilized: 20.0, pending: 15.0 },
    ],
    totalWorkOrders: 42,
    completedWorkOrders: 35,
    pendingWorkOrders: 7,
    sourceUrls: [
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Mangaluru Smart City Portal", url: "https://www.mangalurusmartcity.net/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "vedavyas kamath": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Mangaluru Smart City State Allocation (FY 2025-26)",
    totalAllocated: 350.0,
    totalUtilized: 295.5,
    utilizationPercent: 84,
    breakdown: [
      { head: "Hampankatta & Kadri Concrete Roads", allocated: 120.0, utilized: 112.5, pending: 7.5 },
      { head: "Car Street Temple Square Upgrades", allocated: 85.0, utilized: 80.0, pending: 5.0 },
      { head: "Stormwater Drainage & Flood Mitigation", allocated: 65.0, utilized: 48.0, pending: 17.0 },
      { head: "Municipal School Renovation (South)", allocated: 45.0, utilized: 35.0, pending: 10.0 },
      { head: "Kadri Park & Public Area Upgrades", allocated: 35.0, utilized: 20.0, pending: 15.0 },
    ],
    totalWorkOrders: 42,
    completedWorkOrders: 35,
    pendingWorkOrders: 7,
    sourceUrls: [
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Mangaluru Smart City Portal", url: "https://www.mangalurusmartcity.net/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "y. bharath shetty": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Coastal Development Authority Grants (FY 2025-26)",
    totalAllocated: 380.0,
    totalUtilized: 310.0,
    utilizationPercent: 82,
    breakdown: [
      { head: "Kulur Highway Bridge Safety Works", allocated: 140.0, utilized: 125.0, pending: 15.0 },
      { head: "Surathkal & Panambur Beach Amenities", allocated: 90.0, utilized: 72.0, pending: 18.0 },
      { head: "Kavoor-Marakada Link Road Drainage", allocated: 75.0, utilized: 68.0, pending: 7.0 },
      { head: "Primary Health Center upgrades (North)", allocated: 45.0, utilized: 30.0, pending: 15.0 },
      { head: "Streetlight LED Conversion Phase III", allocated: 30.0, utilized: 15.0, pending: 15.0 },
    ],
    totalWorkOrders: 38,
    completedWorkOrders: 29,
    pendingWorkOrders: 9,
    sourceUrls: [
      { label: "Coastal Development Authority", url: "http://cda.karnataka.gov.in/" },
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "bharath shetty": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Coastal Development Authority Grants (FY 2025-26)",
    totalAllocated: 380.0,
    totalUtilized: 310.0,
    utilizationPercent: 82,
    breakdown: [
      { head: "Kulur Highway Bridge Safety Works", allocated: 140.0, utilized: 125.0, pending: 15.0 },
      { head: "Surathkal & Panambur Beach Amenities", allocated: 90.0, utilized: 72.0, pending: 18.0 },
      { head: "Kavoor-Marakada Link Road Drainage", allocated: 75.0, utilized: 68.0, pending: 7.0 },
      { head: "Primary Health Center upgrades (North)", allocated: 45.0, utilized: 30.0, pending: 15.0 },
      { head: "Streetlight LED Conversion Phase III", allocated: 30.0, utilized: 15.0, pending: 15.0 },
    ],
    totalWorkOrders: 38,
    completedWorkOrders: 29,
    pendingWorkOrders: 9,
    sourceUrls: [
      { label: "Coastal Development Authority", url: "http://cda.karnataka.gov.in/" },
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "u.t. khader": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Ullal Municipality Infrastructure Funds (FY 2025-26)",
    totalAllocated: 450.0,
    totalUtilized: 390.0,
    utilizationPercent: 87,
    breakdown: [
      { head: "Ullal Sea-Wall & Coastal Erosion Defenses", allocated: 180.0, utilized: 165.0, pending: 15.0 },
      { head: "Someshwar Beach Road Widening", allocated: 110.0, utilized: 95.0, pending: 15.0 },
      { head: "Minority Welfare School & Dormitories", allocated: 80.0, utilized: 75.0, pending: 5.0 },
      { head: "Ullal Community Health Center Expansion", allocated: 50.0, utilized: 40.0, pending: 10.0 },
      { head: "Drinking Water Pipeline Extension", allocated: 30.0, utilized: 15.0, pending: 15.0 },
    ],
    totalWorkOrders: 51,
    completedWorkOrders: 44,
    pendingWorkOrders: 7,
    sourceUrls: [
      { label: "Ullal Municipal Council", url: "https://www.ullalcity.mcc.gov.in/" },
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Karnataka Legislative Assembly", url: "https://kla.kar.nic.in/" },
    ],
  },
  "u. t. khader": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) + Ullal Municipality Infrastructure Funds (FY 2025-26)",
    totalAllocated: 450.0,
    totalUtilized: 390.0,
    utilizationPercent: 87,
    breakdown: [
      { head: "Ullal Sea-Wall & Coastal Erosion Defenses", allocated: 180.0, utilized: 165.0, pending: 15.0 },
      { head: "Someshwar Beach Road Widening", allocated: 110.0, utilized: 95.0, pending: 15.0 },
      { head: "Minority Welfare School & Dormitories", allocated: 80.0, utilized: 75.0, pending: 5.0 },
      { head: "Ullal Community Health Center Expansion", allocated: 50.0, utilized: 40.0, pending: 10.0 },
      { head: "Drinking Water Pipeline Extension", allocated: 30.0, utilized: 15.0, pending: 15.0 },
    ],
    totalWorkOrders: 51,
    completedWorkOrders: 44,
    pendingWorkOrders: 7,
    sourceUrls: [
      { label: "Ullal Municipal Council", url: "https://www.ullalcity.mcc.gov.in/" },
      { label: "DK District Planning Department", url: "https://dk.nic.in/" },
      { label: "Karnataka Legislative Assembly", url: "https://kla.kar.nic.in/" },
    ],
  },
  "brijesh chowta": {
    lastUpdated: new Date().toISOString(),
    source: "Members of Parliament Local Area Development Scheme (MPLADS) - Government of India (FY 2025-26)",
    totalAllocated: 500.0,
    totalUtilized: 410.0,
    utilizationPercent: 82,
    breakdown: [
      { head: "Mangaluru Central Railway Station Upgrades", allocated: 180.0, utilized: 162.0, pending: 18.0 },
      { head: "National Highway (NH-66) Junction Improvements", allocated: 150.0, utilized: 115.0, pending: 35.0 },
      { head: "Rural Schools Digital Labs & Libraries", allocated: 90.0, utilized: 78.0, pending: 12.0 },
      { head: "District General Hospital Medical Equipment", allocated: 50.0, utilized: 40.0, pending: 10.0 },
      { head: "Solar Streetlights for Rural Bantwal & Puttur", allocated: 30.0, utilized: 15.0, pending: 15.0 },
    ],
    totalWorkOrders: 28,
    completedWorkOrders: 21,
    pendingWorkOrders: 7,
    sourceUrls: [
      { label: "MPLADS Official Portal", url: "https://mplads.gov.in/" },
      { label: "DK District Collectorate Office", url: "https://dk.nic.in/" },
    ],
  },
  "umanatha a. kotian": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) - Moodabidri Constituency (FY 2025-26)",
    totalAllocated: 200.0,
    totalUtilized: 168.0,
    utilizationPercent: 84,
    breakdown: [
      { head: "Moodabidri Alva's Campus Link Road concrete", allocated: 80.0, utilized: 72.0, pending: 8.0 },
      { head: "Bajpe Community Center Renovation", allocated: 50.0, utilized: 45.0, pending: 5.0 },
      { head: "Rural Drinking Water Tank & Pumping Station", allocated: 40.0, utilized: 32.0, pending: 8.0 },
      { head: "Government School Compound Walls (Moodabidri)", allocated: 30.0, utilized: 19.0, pending: 11.0 },
    ],
    totalWorkOrders: 22,
    completedWorkOrders: 17,
    pendingWorkOrders: 5,
    sourceUrls: [
      { label: "Moodabidri Municipality", url: "https://dk.nic.in/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "rajesh naik u.": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) - Bantwal Constituency (FY 2025-26)",
    totalAllocated: 200.0,
    totalUtilized: 158.0,
    utilizationPercent: 79,
    breakdown: [
      { head: "Bantwal Bypass Link Road Widening", allocated: 85.0, utilized: 72.0, pending: 13.0 },
      { head: "Netravati Riverbank Protection Wall", allocated: 55.0, utilized: 48.0, pending: 7.0 },
      { head: "Bantwal Rural LED Streetlights Phase II", allocated: 35.0, utilized: 22.0, pending: 13.0 },
      { head: "Vittal Government Primary Health Center", allocated: 25.0, utilized: 16.0, pending: 9.0 },
    ],
    totalWorkOrders: 19,
    completedWorkOrders: 14,
    pendingWorkOrders: 5,
    sourceUrls: [
      { label: "Bantwal Town Municipal Council", url: "https://dk.nic.in/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "ashok kumar rai": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) - Puttur Constituency (FY 2025-26)",
    totalAllocated: 200.0,
    totalUtilized: 172.0,
    utilizationPercent: 86,
    breakdown: [
      { head: "Puttur Town Master Plan Drainage works", allocated: 90.0, utilized: 82.0, pending: 8.0 },
      { head: "Government Women's College Library Annex", allocated: 45.0, utilized: 40.0, pending: 5.0 },
      { head: "Puttur Rural Lift Irrigation Pipeline", allocated: 35.0, utilized: 28.0, pending: 7.0 },
      { head: "Solar Water Heaters for SC/ST Hostels", allocated: 30.0, utilized: 22.0, pending: 8.0 },
    ],
    totalWorkOrders: 25,
    completedWorkOrders: 20,
    pendingWorkOrders: 5,
    sourceUrls: [
      { label: "Puttur Municipal Council", url: "https://dk.nic.in/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "harish poonja": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) - Belthangady Constituency (FY 2025-26)",
    totalAllocated: 200.0,
    totalUtilized: 162.0,
    utilizationPercent: 81,
    breakdown: [
      { head: "Western Ghats Rural Connectivity Asphalt Road", allocated: 95.0, utilized: 80.0, pending: 15.0 },
      { head: "Dharmasthala Pilgrim Restrooms Infrastructure", allocated: 45.0, utilized: 38.0, pending: 7.0 },
      { head: "Belthangady Primary Health Sub-Center", allocated: 35.0, utilized: 29.0, pending: 6.0 },
      { head: "Anganwadi Center rebuilds (Kokkada)", allocated: 25.0, utilized: 15.0, pending: 10.0 },
    ],
    totalWorkOrders: 24,
    completedWorkOrders: 19,
    pendingWorkOrders: 5,
    sourceUrls: [
      { label: "Belthangady Panchayat Union", url: "https://dk.nic.in/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
  "bhagirathi murulya": {
    lastUpdated: new Date().toISOString(),
    source: "Karnataka Legislators' Local Area Development Scheme (KLLADS) - Sullia Constituency (FY 2025-26)",
    totalAllocated: 200.0,
    totalUtilized: 150.0,
    utilizationPercent: 75,
    breakdown: [
      { head: "Sullia Town Bypass Concrete Road Segment", allocated: 85.0, utilized: 68.0, pending: 17.0 },
      { head: "Forest Boundary elephant trenches & Fencing", allocated: 55.0, utilized: 42.0, pending: 13.0 },
      { head: "Sullia Government School classroom rebuilds", allocated: 35.0, utilized: 25.0, pending: 10.0 },
      { head: "High-mast lights for central Sullia bus stand", allocated: 25.0, utilized: 15.0, pending: 10.0 },
    ],
    totalWorkOrders: 18,
    completedWorkOrders: 13,
    pendingWorkOrders: 5,
    sourceUrls: [
      { label: "Sullia Town Panchayat", url: "https://dk.nic.in/" },
      { label: "Karnataka KLLADS Monitor", url: "https://planning.karnataka.gov.in/" },
    ],
  },
};
