/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthoritiesIndexRouteImport } from './routes/authorities.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RepresentativesRepIdRouteImport } from './routes/representatives.$repId'
import { Route as AuthoritiesAuthorityIdRouteImport } from './routes/authorities.$authorityId'
import { Route as AdminWardsRouteImport } from './routes/admin.wards'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as AdminRepresentativesRouteImport } from './routes/admin.representatives'
import { Route as AdminJurisdictionRouteImport } from './routes/admin.jurisdiction'
import { Route as AdminIssuesRouteImport } from './routes/admin.issues'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminDevicesRouteImport } from './routes/admin.devices'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAuthoritiesRouteImport } from './routes/admin.authorities'
import { Route as IssuePublicIdSlugRouteImport } from './routes/issue.$publicId.$slug'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthoritiesIndexRoute = AuthoritiesIndexRouteImport.update({
  id: '/authorities/',
  path: '/authorities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentativesRepIdRoute = RepresentativesRepIdRouteImport.update({
  id: '/representatives/$repId',
  path: '/representatives/$repId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthoritiesAuthorityIdRoute = AuthoritiesAuthorityIdRouteImport.update({
  id: '/authorities/$authorityId',
  path: '/authorities/$authorityId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWardsRoute = AdminWardsRouteImport.update({
  id: '/admin/wards',
  path: '/admin/wards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRepresentativesRoute = AdminRepresentativesRouteImport.update({
  id: '/admin/representatives',
  path: '/admin/representatives',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJurisdictionRoute = AdminJurisdictionRouteImport.update({
  id: '/admin/jurisdiction',
  path: '/admin/jurisdiction',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIssuesRoute = AdminIssuesRouteImport.update({
  id: '/admin/issues',
  path: '/admin/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/admin/devices',
  path: '/admin/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthoritiesRoute = AdminAuthoritiesRouteImport.update({
  id: '/admin/authorities',
  path: '/admin/authorities',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuePublicIdSlugRoute = IssuePublicIdSlugRouteImport.update({
  id: '/issue/$publicId/$slug',
  path: '/issue/$publicId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/report': typeof ReportRoute
  '/admin/authorities': typeof AdminAuthoritiesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/jurisdiction': typeof AdminJurisdictionRoute
  '/admin/representatives': typeof AdminRepresentativesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/wards': typeof AdminWardsRoute
  '/authorities/$authorityId': typeof AuthoritiesAuthorityIdRoute
  '/representatives/$repId': typeof RepresentativesRepIdRoute
  '/admin/': typeof AdminIndexRoute
  '/authorities/': typeof AuthoritiesIndexRoute
  '/issue/$publicId/$slug': typeof IssuePublicIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/report': typeof ReportRoute
  '/admin/authorities': typeof AdminAuthoritiesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/jurisdiction': typeof AdminJurisdictionRoute
  '/admin/representatives': typeof AdminRepresentativesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/wards': typeof AdminWardsRoute
  '/authorities/$authorityId': typeof AuthoritiesAuthorityIdRoute
  '/representatives/$repId': typeof RepresentativesRepIdRoute
  '/admin': typeof AdminIndexRoute
  '/authorities': typeof AuthoritiesIndexRoute
  '/issue/$publicId/$slug': typeof IssuePublicIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/report': typeof ReportRoute
  '/admin/authorities': typeof AdminAuthoritiesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/jurisdiction': typeof AdminJurisdictionRoute
  '/admin/representatives': typeof AdminRepresentativesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/wards': typeof AdminWardsRoute
  '/authorities/$authorityId': typeof AuthoritiesAuthorityIdRoute
  '/representatives/$repId': typeof RepresentativesRepIdRoute
  '/admin/': typeof AdminIndexRoute
  '/authorities/': typeof AuthoritiesIndexRoute
  '/issue/$publicId/$slug': typeof IssuePublicIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/explore'
    | '/leaderboard'
    | '/report'
    | '/admin/authorities'
    | '/admin/categories'
    | '/admin/devices'
    | '/admin/feedback'
    | '/admin/issues'
    | '/admin/jurisdiction'
    | '/admin/representatives'
    | '/admin/rules'
    | '/admin/wards'
    | '/authorities/$authorityId'
    | '/representatives/$repId'
    | '/admin/'
    | '/authorities/'
    | '/issue/$publicId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/explore'
    | '/leaderboard'
    | '/report'
    | '/admin/authorities'
    | '/admin/categories'
    | '/admin/devices'
    | '/admin/feedback'
    | '/admin/issues'
    | '/admin/jurisdiction'
    | '/admin/representatives'
    | '/admin/rules'
    | '/admin/wards'
    | '/authorities/$authorityId'
    | '/representatives/$repId'
    | '/admin'
    | '/authorities'
    | '/issue/$publicId/$slug'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/explore'
    | '/leaderboard'
    | '/report'
    | '/admin/authorities'
    | '/admin/categories'
    | '/admin/devices'
    | '/admin/feedback'
    | '/admin/issues'
    | '/admin/jurisdiction'
    | '/admin/representatives'
    | '/admin/rules'
    | '/admin/wards'
    | '/authorities/$authorityId'
    | '/representatives/$repId'
    | '/admin/'
    | '/authorities/'
    | '/issue/$publicId/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ReportRoute: typeof ReportRoute
  AdminAuthoritiesRoute: typeof AdminAuthoritiesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminIssuesRoute: typeof AdminIssuesRoute
  AdminJurisdictionRoute: typeof AdminJurisdictionRoute
  AdminRepresentativesRoute: typeof AdminRepresentativesRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminWardsRoute: typeof AdminWardsRoute
  AuthoritiesAuthorityIdRoute: typeof AuthoritiesAuthorityIdRoute
  RepresentativesRepIdRoute: typeof RepresentativesRepIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AuthoritiesIndexRoute: typeof AuthoritiesIndexRoute
  IssuePublicIdSlugRoute: typeof IssuePublicIdSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorities/': {
      id: '/authorities/'
      path: '/authorities'
      fullPath: '/authorities/'
      preLoaderRoute: typeof AuthoritiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representatives/$repId': {
      id: '/representatives/$repId'
      path: '/representatives/$repId'
      fullPath: '/representatives/$repId'
      preLoaderRoute: typeof RepresentativesRepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorities/$authorityId': {
      id: '/authorities/$authorityId'
      path: '/authorities/$authorityId'
      fullPath: '/authorities/$authorityId'
      preLoaderRoute: typeof AuthoritiesAuthorityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wards': {
      id: '/admin/wards'
      path: '/admin/wards'
      fullPath: '/admin/wards'
      preLoaderRoute: typeof AdminWardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/representatives': {
      id: '/admin/representatives'
      path: '/admin/representatives'
      fullPath: '/admin/representatives'
      preLoaderRoute: typeof AdminRepresentativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jurisdiction': {
      id: '/admin/jurisdiction'
      path: '/admin/jurisdiction'
      fullPath: '/admin/jurisdiction'
      preLoaderRoute: typeof AdminJurisdictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/issues': {
      id: '/admin/issues'
      path: '/admin/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AdminIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/admin/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/authorities': {
      id: '/admin/authorities'
      path: '/admin/authorities'
      fullPath: '/admin/authorities'
      preLoaderRoute: typeof AdminAuthoritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue/$publicId/$slug': {
      id: '/issue/$publicId/$slug'
      path: '/issue/$publicId/$slug'
      fullPath: '/issue/$publicId/$slug'
      preLoaderRoute: typeof IssuePublicIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  LeaderboardRoute: LeaderboardRoute,
  ReportRoute: ReportRoute,
  AdminAuthoritiesRoute: AdminAuthoritiesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminIssuesRoute: AdminIssuesRoute,
  AdminJurisdictionRoute: AdminJurisdictionRoute,
  AdminRepresentativesRoute: AdminRepresentativesRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminWardsRoute: AdminWardsRoute,
  AuthoritiesAuthorityIdRoute: AuthoritiesAuthorityIdRoute,
  RepresentativesRepIdRoute: RepresentativesRepIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AuthoritiesIndexRoute: AuthoritiesIndexRoute,
  IssuePublicIdSlugRoute: IssuePublicIdSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
